#! /bin/sh
set -euo pipefail

sxhkd &
compton &
hsetroot -full ~/mybg/bg7.jpg -tint '#9ea8ba' &

bspc monitor -d I II III IV V VI

bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^4' state=floating follow=on
bspc rule -a Firefox desktop='^2'
bspc rule -a vlc desktop='^5' state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
